[package]
name = "each_cons"
description = "Port of ruby's Enumerable#each_cons."
authors = ["Ulysse Buonomo <buonomo.ulysse@gmail.com>"]
homepage = "https://docs.rs/each_cons/0.2.0"
repository = "https://github.com/BuonOmo/each_cons.rs"
license = "MIT"
version = "0.2.0"
edition = "2018"
